### ISSUE TITLE
Pronterface Windows 64 3.10 issue 

### ISSUE THREAD

**Issue by ASimplePseudonym** [DivingDuck/Printrun#22]
I am very inexperienced with anything coding, but have purchased an anycubic kobra go and am trying to use pronterface to calibrate my esteps and do PID tuning. The latest official release of Pronterface will fail to execute the script so I have been trying to use your build but am encountering errors. I can get pronterface to start and the interface pops up but as soon as I try to connect to the printer via USB cable it gives me this error:

Connecting...
--- Logging error ---
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

This then repeats any time I try to close something or change anything until I force quit through task manager. Again I am a total noob at coding so any advice you can give would be a huge help.

**Comment by ASimplePseudonym** [comment]
To add on to this, in case it helps, when trying to close the pronterface window this error is displayed:

Not connected to printer.
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
  File "printrun\pronterface.py", line 108, in write
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "printrun\printcore.py", line 150, in logError
  File "printrun\pronsole.py", line 297, in logError
  File "logging\__init__.py", line 2105, in error
  File "logging\__init__.py", line 1506, in error
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
  File "logging\__init__.py", line 1021, in handleError
  File "printrun\pronterface.py", line 108, in write
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by DivingDuck** [comment]
Hi @ASimplePseudonym,
this looks quite ~~annoying~~ weird. If I had to make a guess, I would say your installation isn't going well and there is maybe a write protection or AV blocking issue. Can you please tell me and check:

- Where do you install printrun?
- Is there a file named printrunconf.ini in your user directory (like: c:\Users\\**Your_User_Name**\\ where Your_User_Name is your windows user name)?
- Is there a directory named c:\Users\\**Your_User_Name**\AppData\Local\Printrun\ where Your_User_Name is your windows user name)?

The last one is in a hidden directory of windows, so you need to enable hidden files/directories in your Explorer.

I just check my latest packages and they are running well on my Windows 10 x64 computer

**Comment by DivingDuck** [comment]
backslash in path was not shown

**Comment by ASimplePseudonym** [comment]
Hey @DivingDuck! 

I really appreciate the help! As I said this is the first time I am using pronterface so its very possible I have installed incorrectly. I followed this article: https://all3dp.com/2/pronterface-how-to-download-install-and-set-it-up/ where it said for the windows 64 version to download the latest version from the pronterface site and then extract it into the folder you'd like to install in, then run the programme and set up from there.

I did this and for my current purposes I just moved it into my documents folder. 

I do not have the file labelled printrunconf.ini in my user directory but I do have the directory named :\Users*Your_User_Name*\AppData\Local\Printrun\ 

If I have installed incorrectly or in the wrong area please let me know, and thanks again for helping me troubleshoot!

**Comment by DivingDuck** [comment]
Please download this version: https://github.com/DivingDuck/Printrun/suites/9988878289/artifacts/484721506

First delete the directory:
 \Users\Your_User_Name\AppData\Local\Printrun\

Then create a new directory  \Users\Your_User_Name\Printrun and copy the extracted file pronterface.exe from the download.

Optional: Create a file link from pronterface.exe (right click, create link) and move it to your desktop. This way you can run Pronterface directly from your desktop

Then start Pronterface. You will maybe be ask from windows AV if you really want to run this program. You need to allow this the first time.
Sorry, this is from a german Windows version, but maybe it helps : 
![PronterfaceFirstTime1](https://user-images.githubusercontent.com/8143022/209446276-cb4e28cd-4d2b-4794-b092-32610dcfd963.PNG)
![PronterfaceFirstTime2](https://user-images.githubusercontent.com/8143022/209446286-a42abce0-fea8-4f8b-8ebd-27f463f7a368.PNG)

**Comment by DivingDuck** [comment]
@ASimplePseudonym,
did you solve your problem?

**Comment by ASimplePseudonym** [comment]
Unfortunately it is still having the same issue, i'm not sure what else to try

**Comment by ASimplePseudonym** [comment]
I have been trying to troubleshoot but cannot see what may be incorrect. The only thing I can think may be affecting it is I think my computer is running windows 11 not windows 10?

**Comment by DivingDuck** [comment]
Windows 11 should be fine. Had you download the file from my answer above and install as I mentioned?
Can you please make some screen shots and attach it here?
Something like this:
(Start Pronterfce, make a connection and then a screen shot)
![Pronterface](https://user-images.githubusercontent.com/8143022/210100938-d5c3c8b0-b0c7-4b0c-a614-0fc16834e6bd.PNG)

**Comment by ASimplePseudonym** [comment]
When trying to connect my display looks like this:
![Screenshot (1)](https://user-images.githubusercontent.com/121179695/210101534-142a6219-9ea2-44f1-a753-f72131782130.png)

**Comment by ASimplePseudonym** [comment]
And yes downloaded the above version, deleted the current \Users\Your_User_Name\AppData\Local\Printrun\ directory and made a new one copying the extracted file from the download into it and making the desktop link as well.

**Comment by ASimplePseudonym** [comment]
When trying to close or restart pronterface this is how the display reacts:
![Screenshot (2)](https://user-images.githubusercontent.com/121179695/210101882-60ceebe5-6ba4-436c-8fa9-d129d7137a8c.png)

**Comment by DivingDuck** [comment]
Can you please attach the file printrunconf.ini

**Comment by DivingDuck** [comment]
@ASimplePseudonym,
I just took a closer look to your attachments. In both pictures Printrun seems to indicate that it is not connected to your printer. E.g. there are no temperature information's in the left window. There should be at least a text line with those reported values.
Please check your Settings and enable logging like in attached screen shot:
![PronterfaceSettingsUI](https://user-images.githubusercontent.com/8143022/210104154-08748fd2-9eb8-42ff-95fd-4403b40b30af.PNG)
Log path: c:\Users\Armin\Printrun.log
You need to change this to your user path. Please attach this file as well.

**Comment by ASimplePseudonym** [comment]
Thank You! this helped, it is now at least saying the printer is connected, I have not tried to run any commands yet though

**Comment by DivingDuck** [comment]
Good to hear.
Set up first your printer dimensions like:
![PronterfaceSettingsUI_2](https://user-images.githubusercontent.com/8143022/210105208-258f045d-8d43-4e37-aaa0-214301da3e5c.PNG)
Then make a homing so your printer knows its coordinates.
Good luck. Let me know how it works out for you.

**Comment by ASimplePseudonym** [comment]
Thanks so much for that! Can I ask how to go about taking a homing?

**Comment by DivingDuck** [comment]
Homing (move to origin):
There are two ways to do it in Pronterface.
You can use the gcode command G28 and wrote it in the terminal window (right side):
![PronterfaceHomingAxes2](https://user-images.githubusercontent.com/8143022/210109973-1ada2765-2469-4763-b7ca-ac1a8802bba7.PNG)

Or you can use the house icons on the left side:
![PronterfaceHomingAxes](https://user-images.githubusercontent.com/8143022/210110037-a06506de-4b85-494e-a5ee-09aca431d7d8.PNG)
House with no axis will home all axis (left bottom) and the other three icons only the specified axis.

**Comment by DivingDuck** [comment]
This page is as well helpful if you want to know more about gcodes
https://reprap.org/wiki/G-code

**Comment by DivingDuck** [comment]
Guess, your issue is solved. I will close the issue.
Best regards, DD
